blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/pl3xgaming/Purpur/discussions/new
    about: Suggest an idea for Purpur
  - name: Purpur Discord
    url: https://purpur.pl3x.net/discord
    about: If you are having issues with timings or have other minor issues, come join our Discord server for help!
