name: Build Purpur 1.16.5
on:
  push:
    branches: [ ver/1.16.5 ]
  pull_request:
    branches: [ ver/1.16.5 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Apply patches
        run: ./gradlew applyPatches
      - name: Build
        run: ./gradlew build
      - name: Paperclip
        run: ./gradlew paperclip
      - name: upload paperclip
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Paper/work/Paperclip/assembly/target/
